image: node:18-alpine

stages:
  - test_stage
  - build_stage
  - deploy_stage
#   - push_stage

test:
    stage: test_stage
    script:
        - npm i
        - npm run test
    artifacts:
        when: always
        paths:
        - coverage/


build:
    stage: build_stage
    script:
        - docker --version
        - docker build -t sc-backend .
    tags:
        - localshell
        - localrunner 

deploy:
  stage: deploy_stage
  script:
    - docker stop scbackendcontainer || true && docker rm scbackendcontainer || true
    - docker run -d --name scbackendcontainer -p 8080:8080 sc-backend
  tags:
    - localshell
    - localrunner
